Add DNS timeout tags
logstash-plugins/logstash-filter-dns pull request #53
Opened 2019-05-08 18:47 UTC by AlessandroMenti

This PR adds a tag whenever a DNS lookup times out and changes the related logging level to `debug`, fixing #47.

I'm marking this PR as WIP because I like the option of adding a tag on each kind of failure (#24) more, but I'm not fully sure if I should just add a generic "failure" tag for each kind of error that might occur (DNS lookup failure/timeout error...) or if there should be a way to associate each kind of failure to a specific tag.

2019-12-02 17:16 UTC, davewat commented
Millions of DNS warnings for expected DNS failures filling logs every hour.  Would love to see this PR merged ASAP.  Thanks!

2020-05-27 10:16 UTC, KrishnanandSingh commented
This would be a useful feature. Can't wait to see this merged.

2021-05-18 07:46 UTC, kares requested changes
:+1: this is looking good.

could you maybe [bump the version](https://github.com/logstash-plugins/logstash-filter-dns/pull/61/files#diff-c5f65487f47fdda596f8ff4c73a5c20dbe7f2b247021562617f834ea9367a9d9R4) and add a changelog entry (should be a next minor e.g. 3.2.0 given the new feature)

2021-05-18 07:46 UTC, kares commented on lib/logstash/filters/dns.rb
> +        @logger.debug("DNS: timeout on resolving the hostname.",
could we maybe keep these at the `info` level?

2022-01-29 16:41 UTC, jsvd commented
bump minor

2022-06-24 19:02 UTC, closed without merging